name = "backend"
compatibility_date = "2024-08-14"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiOGU1MTJhMTctZjBkZi00MzM4LWE2MjgtMDZmYWZjMjI2MjQ0IiwidGVuYW50X2lkIjoiOWMwODkyYjY5ZmZjYjhhNDRmNWIzOTE5YzVkMjNlMjA3NzJlMjllNGM0OTg4MWJjNWNiM2UyYmM5OTdiOTlmNSIsImludGVybmFsX3NlY3JldCI6IjRkMWJiY2IxLTA5YzctNDJiNC05MDM0LTc2ZTQ2Nxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

JWT_SECRET="pdgvasdwecbfhstpdgvasxxxxxxxxxxxxxxxx"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE" 
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"